### ISSUE TITLE
A required class was missing while executing pl.project13.maven:git-commit-id-plugin:4.0.2:revision

### ISSUE THREAD

**Issue by glhez** [git-commit-id/git-commit-id-maven-plugin#521]
### Describe the bug
In Eclipse 2020.09, with Java 15/11, I often run into this error: 

> Execution git-fetch-revision of goal pl.project13.maven:git-commit-id-plugin:4.0.2:revision failed: A required class was missing > while executing pl.project13.maven:git-commit-id-plugin:4.0.2:revision: com/fasterxml/jackson/core/io/CharTypes

There is a stack in the Eclipse Problem view (which I'll put below).
The class (jackson) is not always the same.

This never happens invoking maven directly (mvn package).

### Steps to Reproduce

Not sure about steps to reproduce: I am in Eclipse, and I do refresh my project (Alt + F5), or Eclipse does it automatically at startup. The git-commit-id-plugin is probably bound to some phase and is being run by Eclipse / m2e.

Note: you can also see configuration here https://github.com/glhez/project-settings/blob/master/pom.xml#L314

```xml
<plugin>
        <groupId>pl.project13.maven</groupId>
        <artifactId>git-commit-id-plugin</artifactId>
        <executions>
          <execution>
            <id>git-fetch-revision</id>
            <goals> <goal>revision</goal> </goals>
            <phase>initialize</phase>
            <configuration>
              <dotGitDirectory>${session.executionRootDirectory}/.git</dotGitDirectory>
              <generateGitPropertiesFile>true</generateGitPropertiesFile>
              <generateGitPropertiesFilename>${project.build.outputDirectory}/META-INF/git.properties</generateGitPropertiesFilename>
              <skipPoms>true</skipPoms>
              <includeOnlyProperties>
                <includeOnlyProperty>^\Qgit.commit.id\E$</includeOnlyProperty>
                <includeOnlyProperty>^\Qgit.commit.id.full\E$</includeOnlyProperty>
                <includeOnlyProperty>^\Qgit.commit.time\E$</includeOnlyProperty>
                <includeOnlyProperty>^\Qgit.dirty\E$</includeOnlyProperty>
                <includeOnlyProperty>^\Qgit.branch\E$</includeOnlyProperty>
                <includeOnlyProperty>^\Qgit.closest.tag.name\E$</includeOnlyProperty>
              </includeOnlyProperties>
              <!-- <verbose>true</verbose> -->
              <abbrevLength>40</abbrevLength>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

- Is there a (public) project where this issue can be reproduced? 

I don't think a project in particular is relevant.
You may try importing these two repos as Maven project in Eclipse:

https://github.com/glhez/project-settings/
https://github.com/glhez/eclipse-plugins

- Include any stack-traces or any error messages

```text
Execution git-fetch-revision of goal pl.project13.maven:git-commit-id-plugin:4.0.2:revision failed: A required class was missing while executing pl.project13.maven:git-commit-id-plugin:4.0.2:revision: com/fasterxml/jackson/core/io/CharTypes
-----------------------------------------------------
realm =    plugin>pl.project13.maven:git-commit-id-plugin:4.0.2
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/E:/apps/data/maven/pl/project13/maven/git-commit-id-plugin/4.0.2/git-commit-id-plugin-4.0.2.jar
urls[1] = file:/E:/apps/data/maven/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
urls[2] = file:/E:/apps/data/maven/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
urls[3] = file:/E:/apps/data/maven/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
urls[4] = file:/E:/apps/data/maven/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
urls[5] = file:/E:/apps/data/maven/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.jar
urls[6] = file:/E:/apps/data/maven/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[7] = file:/E:/apps/data/maven/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
urls[8] = file:/E:/apps/data/maven/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
urls[9] = file:/E:/apps/data/maven/pl/project13/maven/git-commit-id-plugin-core/4.0.2/git-commit-id-plugin-core-4.0.2.jar
urls[10] = file:/E:/apps/data/maven/org/eclipse/jgit/org.eclipse.jgit/5.8.1.202007141445-r/org.eclipse.jgit-5.8.1.202007141445-r.jar
urls[11] = file:/E:/apps/data/maven/com/googlecode/javaewah/JavaEWAH/1.1.7/JavaEWAH-1.1.7.jar
urls[12] = file:/E:/apps/data/maven/joda-time/joda-time/2.10.6/joda-time-2.10.6.jar
urls[13] = file:/E:/apps/data/maven/com/fasterxml/jackson/core/jackson-databind/2.11.2/jackson-databind-2.11.2.jar
urls[14] = file:/E:/apps/data/maven/com/fasterxml/jackson/core/jackson-annotations/2.11.2/jackson-annotations-2.11.2.jar
urls[15] = file:/E:/apps/data/maven/com/fasterxml/jackson/core/jackson-core/2.11.2/jackson-core-2.11.2.jar
urls[16] = file:/E:/apps/data/maven/nu/studer/java-ordered-properties/1.0.4/java-ordered-properties-1.0.4.jar
urls[17] = file:/E:/apps/data/maven/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
Number of foreign imports: 5
import: Entry[import org.sonatype.plexus.build.incremental from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.Scanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.DirectoryScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.AbstractScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import  from realm ClassRealm[project>com.github.glhez.eclipse:com.github.glhez.eclipse.features.all:1.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]

-----------------------------------------------------
 (pl.project13.maven:git-commit-id-plugin:4.0.2:revision:git-fetch-revision:initialize)

org.apache.maven.plugin.PluginExecutionException: Execution git-fetch-revision of goal pl.project13.maven:git-commit-id-plugin:4.0.2:revision failed: A required class was missing while executing pl.project13.maven:git-commit-id-plugin:4.0.2:revision: com/fasterxml/jackson/core/io/CharTypes
-----------------------------------------------------
realm =    plugin>pl.project13.maven:git-commit-id-plugin:4.0.2
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/E:/apps/data/maven/pl/project13/maven/git-commit-id-plugin/4.0.2/git-commit-id-plugin-4.0.2.jar
urls[1] = file:/E:/apps/data/maven/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
urls[2] = file:/E:/apps/data/maven/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
urls[3] = file:/E:/apps/data/maven/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
urls[4] = file:/E:/apps/data/maven/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
urls[5] = file:/E:/apps/data/maven/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.jar
urls[6] = file:/E:/apps/data/maven/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[7] = file:/E:/apps/data/maven/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
urls[8] = file:/E:/apps/data/maven/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
urls[9] = file:/E:/apps/data/maven/pl/project13/maven/git-commit-id-plugin-core/4.0.2/git-commit-id-plugin-core-4.0.2.jar
urls[10] = file:/E:/apps/data/maven/org/eclipse/jgit/org.eclipse.jgit/5.8.1.202007141445-r/org.eclipse.jgit-5.8.1.202007141445-r.jar
urls[11] = file:/E:/apps/data/maven/com/googlecode/javaewah/JavaEWAH/1.1.7/JavaEWAH-1.1.7.jar
urls[12] = file:/E:/apps/data/maven/joda-time/joda-time/2.10.6/joda-time-2.10.6.jar
urls[13] = file:/E:/apps/data/maven/com/fasterxml/jackson/core/jackson-databind/2.11.2/jackson-databind-2.11.2.jar
urls[14] = file:/E:/apps/data/maven/com/fasterxml/jackson/core/jackson-annotations/2.11.2/jackson-annotations-2.11.2.jar
urls[15] = file:/E:/apps/data/maven/com/fasterxml/jackson/core/jackson-core/2.11.2/jackson-core-2.11.2.jar
urls[16] = file:/E:/apps/data/maven/nu/studer/java-ordered-properties/1.0.4/java-ordered-properties-1.0.4.jar
urls[17] = file:/E:/apps/data/maven/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
Number of foreign imports: 5
import: Entry[import org.sonatype.plexus.build.incremental from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.Scanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.DirectoryScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.AbstractScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import  from realm ClassRealm[project>com.github.glhez.eclipse:com.github.glhez.eclipse.features.all:1.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]

-----------------------------------------------------

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:171)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:332)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.lambda$8(MavenImpl.java:1380)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1379)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:54)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:135)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:169)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$1(MavenBuilder.java:114)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:114)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:197)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.maven.plugin.PluginContainerException: A required class was missing while executing pl.project13.maven:git-commit-id-plugin:4.0.2:revision: com/fasterxml/jackson/core/io/CharTypes
-----------------------------------------------------
realm =    plugin>pl.project13.maven:git-commit-id-plugin:4.0.2
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/E:/apps/data/maven/pl/project13/maven/git-commit-id-plugin/4.0.2/git-commit-id-plugin-4.0.2.jar
urls[1] = file:/E:/apps/data/maven/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
urls[2] = file:/E:/apps/data/maven/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
urls[3] = file:/E:/apps/data/maven/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
urls[4] = file:/E:/apps/data/maven/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
urls[5] = file:/E:/apps/data/maven/org/codehaus/plexus/plexus-utils/2.0.4/plexus-utils-2.0.4.jar
urls[6] = file:/E:/apps/data/maven/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
urls[7] = file:/E:/apps/data/maven/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
urls[8] = file:/E:/apps/data/maven/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
urls[9] = file:/E:/apps/data/maven/pl/project13/maven/git-commit-id-plugin-core/4.0.2/git-commit-id-plugin-core-4.0.2.jar
urls[10] = file:/E:/apps/data/maven/org/eclipse/jgit/org.eclipse.jgit/5.8.1.202007141445-r/org.eclipse.jgit-5.8.1.202007141445-r.jar
urls[11] = file:/E:/apps/data/maven/com/googlecode/javaewah/JavaEWAH/1.1.7/JavaEWAH-1.1.7.jar
urls[12] = file:/E:/apps/data/maven/joda-time/joda-time/2.10.6/joda-time-2.10.6.jar
urls[13] = file:/E:/apps/data/maven/com/fasterxml/jackson/core/jackson-databind/2.11.2/jackson-databind-2.11.2.jar
urls[14] = file:/E:/apps/data/maven/com/fasterxml/jackson/core/jackson-annotations/2.11.2/jackson-annotations-2.11.2.jar
urls[15] = file:/E:/apps/data/maven/com/fasterxml/jackson/core/jackson-core/2.11.2/jackson-core-2.11.2.jar
urls[16] = file:/E:/apps/data/maven/nu/studer/java-ordered-properties/1.0.4/java-ordered-properties-1.0.4.jar
urls[17] = file:/E:/apps/data/maven/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
Number of foreign imports: 5
import: Entry[import org.sonatype.plexus.build.incremental from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.Scanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.DirectoryScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import org.codehaus.plexus.util.AbstractScanner from realm ClassRealm[plexus.core, parent: null]]
import: Entry[import  from realm ClassRealm[project>com.github.glhez.eclipse:com.github.glhez.eclipse.features.all:1.0.0-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]

-----------------------------------------------------

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:169)
	... 30 more
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/io/CharTypes
	at com.fasterxml.jackson.core.io.JsonStringEncoder.<clinit>(JsonStringEncoder.java:24)
	at com.fasterxml.jackson.core.io.SerializedString.<clinit>(SerializedString.java:22)
	at com.fasterxml.jackson.core.util.DefaultPrettyPrinter.<clinit>(DefaultPrettyPrinter.java:28)
	at com.fasterxml.jackson.core.JsonFactory.<clinit>(JsonFactory.java:179)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:608)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:539)
	at pl.project13.core.PropertiesFileGenerator.<clinit>(PropertiesFileGenerator.java:37)
	at pl.project13.maven.git.GitCommitIdMojo.execute(GitCommitIdMojo.java:525)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	... 30 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.io.CharTypes
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 39 more
```

### Expected behavior

No error :)

### Additional context
For reproducibility please provide the following:

- Plugin version: 4.0.2
- Java Version: 11.0.8 + 15.0
- Maven Version: 3.6.3 (the version embedded in Eclipse is also a 3.6.3)
- Running on Windows 10
- Not sure which step m2e execute during the configuration phase.

> Feel free to add any other context or screenshots about the bug.

In Maven Installations (in Eclipse Preference), I am using the version bundled in Eclipse which is a 3.6.3.

**Comment by TheSnoozer** [comment]
Hello,
thank you for reporting! I have seen a similar issue before and the fix was to remove the `.m2`-folder (as outlined https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/398#issuecomment-441082353). Could you perhaps try if this solves this issue in your case too? Perhaps first rename it?

**Comment by glhez** [comment]
Hello,

I think I tried (for a completely different reason) to trash the repo, but to no effect. I'll retry again.
I will also try to ask maven to check dependency integrity (https://books.sonatype.com/mvnref-book/reference/running-sect-options.html#running-sect-deps-option).

**Comment by TheSnoozer** [comment]
Hello, I just wanted to check-in into this. Have you made any further observations, or is this still an issue? I wonder how one could reproduce it...

**Comment by glhez** [comment]
Since I purged my m2 repo, I could not reproduce.

**Comment by TheSnoozer** [comment]
Thanks for the feedback! I'd assume some dependency was not downloaded correctly yielding to the issue observed.
