### ISSUE TITLE
Cannot save config file 'FileBasedConfig[H:\.config\jgit\config]'

### ISSUE THREAD

**Issue by bernardpaulus** [git-commit-id/git-commit-id-maven-plugin#566]
### Describe the bug

During maven build, we observe the following error message from git-commit-id-maven-plugin 4.0.5:

    Cannot save config file 'FileBasedConfig[H:\.config\jgit\config]'

The H: drive is a network drive where our home dir is set

### Steps to Reproduce
- `mvn -version`
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\<redacted>\tools\maven\3.6.3
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: C:\Program Files\Java\JDK8\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
- Plugin config:
```xml
      <plugin>
        <groupId>pl.project13.maven</groupId>
        <artifactId>git-commit-id-plugin</artifactId>
        <version>4.0.5</version>
        <configuration>
          <failOnNoGitDirectory>false</failOnNoGitDirectory>
          <offline>true</offline>
        </configuration>
      </plugin>
```
- no public build
- Observed error:
```
    Cannot save config file 'FileBasedConfig[H:\.config\jgit\config]'
```
This error doesn not prevents the maven build from being executed with success. However, intelliJ Community 2019.3 spots it as an error:
![image](https://user-images.githubusercontent.com/1094636/124919562-af3ea800-dff6-11eb-9e9d-be0dc58d7ff2.png)

### Expected behavior
- no error message printed

### Additional context

This might be similar to https://www.eclipse.org/forums/index.php/t/1103395/

**Comment by TheSnoozer** [comment]
Hello,
thank you for reporting this issue here! When I read the linked ticket (https://bugs.eclipse.org/bugs/show_bug.cgi?id=566170) correctly this should be fixed whenever we update the jgit-library to version 5.9?!?

For the time being you could potentially switch to the native git binary via ``<useNativeGit>false</useNativeGit>`` which would help avoid that issue since it doesn't rely on jgit.

**Comment by TheSnoozer** [comment]
Ah I just realized that this is essentially a duplicate of https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/518. At least it's the same issue. Perhaps a different context....not sure if I should keep both issues open, but I guess it doesn't hurt either.

**Comment by bernardpaulus** [comment]
The difference with #518 is that there the build fails while in this case it does not

thanks for the useNativeGit tip!

**Comment by TheSnoozer** [comment]
thanks for pointing out that difference!
Could you perhaps also confirm which version you are using?
If you are on 4.0.5 this should already include jgit `5.12.0.202106070339-r` (see https://github.com/git-commit-id/git-commit-id-maven-plugin/blob/v4.0.5/core/pom.xml#L20). Based on the closed bug report (https://bugs.eclipse.org/bugs/show_bug.cgi?id=566170) this should have been fixed in 5.9.X....hence this would make me suspect that it is not fixed properly and would deserve a new ticket, or to have the old to be reopened.

**Comment by diceit-git** [comment]
Same Problem with 4.9.10:
```
[INFO] --- git-commit-id-plugin:4.9.10:revision (default) ...
[ERROR] Cannot save config file 'FileBasedConfig[H:\.config\jgit\config]'
java.io.IOException: Creating directories for H:\.config\jgit failed
```

**Comment by TheSnoozer** [comment]
Sorry it should have been `<useNativeGit>true</useNativeGit>` I have updated my initial comment.

**Comment by PawelLipski** [comment]
@TheSnoozer we're actually observing the same problem now in https://github.com/VirtusLab/git-machete-intellij-plugin/issues/1239 ... despite using the latest JGit (`6.3.0.202209071007-r`) ☹️

**Comment by TheSnoozer** [comment]
Thanks for raising this! I guess we should then (re-)open a ticket with jgit :-(

**Comment by PawelLipski** [comment]
Yes, if you could 🙏🏻 pls mention me on that ticket (if that's on GitHub) or provide the link for the ticket (otherwise) 🎫

**Comment by PawelLipski** [comment]
Actually... seems that it can be closed: https://github.com/VirtusLab/git-machete-intellij-plugin/issues/1239#issuecomment-1274786576

**Comment by lars06** [comment]
Hi everyone. I came across the same [issue](https://github.com/n0mer/gradle-git-properties/issues/224) on the gradle [plugin](https://github.com/n0mer/gradle-git-properties) for git commit id.

To rule solutions out, I tried to create the .config directory manually and that works correctly. I also tried to manually exclude the jgit dependency and manually include newer versions which still produced the error.

Did anyone find the cause of this that could maybe be applied to the gradle plugin also? Thanks

**Comment by garretwilson** [comment]
I just used the very latest JGit. I tried it on AWS Lambda and realize it's been saving this `~/.config/jgit` stuff without telling me, even on my machine! On AWS lambda it did this:

```
2023-06-10 13:41:43  ERROR FS - Cannot save config file 'FileBasedConfig[/home/sbx_user1051/.config/jgit/config]'
java.io.IOException: Creating directories for /home/sbx_user1051/.config/jgit failed
	at org.eclipse.jgit.util.FileUtils.mkdirs(FileUtils.java:413) ~[task/:?]
	at org.eclipse.jgit.internal.storage.file.LockFile.lock(LockFile.java:140) ~[task/:?]
	at org.eclipse.jgit.storage.file.FileBasedConfig.save(FileBasedConfig.java:184) ~[task/:?]
	at org.eclipse.jgit.util.FS$FileStoreAttributes.saveToConfig(FS.java:766) ~[task/:?]
	at org.eclipse.jgit.util.FS$FileStoreAttributes.lambda$5(FS.java:448) ~[task/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

A library shouldn't be making config files in my user directory without telling me. I don't want them to begin with, even when running on my own machine. How do disable this behavior?
